apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: arc
  labels:
    app: web
spec:
  containers:
    - name: web
      image: contosorenewable.azurecr.io/contosorenewableenergywindfarmmonitoring:test9
      ports:
        - name: frontend
          containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: appservice
  namespace: arc
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: db-login-secret
  namespace: arc
data:
  password: WXVrb245MDA=
  username: YXJjYWRtaW4=
type: Opaque
---
apiVersion: sql.arcdata.microsoft.com/v1alpha1
kind: sqlmanagedinstance
metadata:
  name: db
  namespace: arc
spec:
  service:
    type: ClusterIP
  storage:
    data:
      className: default
      size: 5Gi
    logs:
      className: default
      size: 1Gi